#Travis CI configuration for MAP-Tk
# See http://travis-ci.org/Kitware/maptk/

sudo: false

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6

cache:
  directories:
  - $HOME/deps

before_script:
  - bash .travis/install-deps.sh

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libproj-dev
    - libgl1-mesa-dev
    - libxt-dev
    - libqt4-dev
    - libatlas-base-dev

script:
  - export PATH=$HOME/deps/bin:$PATH
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER
          -DMAPTK_ENABLE_GUI:BOOL=ON
          -DMAPTK_ENABLE_TESTING:BOOL=ON
          ../
  - make -j2
  - ctest
